# Generated by Django 5.0.1 on 2025-06-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pasillo', 'Pasillo'), ('estante', 'Estante'), ('bodega', 'Bodega'), ('vitrina', 'Vitrina'), ('deposito', 'Depósito'), ('otro', 'Otro')], default='estante', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_maxima', models.IntegerField(blank=True, help_text='Cantidad máxima de productos', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='inventario.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['sucursal', 'tipo', 'codigo'],
                'unique_together': {('sucursal', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion_detallada',
            field=models.ForeignKey(blank=True, help_text='Ubicación específica dentro de la sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacion'),
        ),
    ]
