# Generated by Django 5.0.1 on 2025-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto (JPG, PNG, máx. 5MB)', null=True, upload_to='productos/%Y/%m/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='inventario_producto',
        ),
    ]
