# Generated by Django 5.0.1 on 2025-06-13 16:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_options_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio actual del producto', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_actualizado',
            field=models.DateTimeField(blank=True, help_text='Fecha de última actualización del precio', null=True),
        ),
    ]
