# Generated by Django 5.0.1 on 2025-06-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_precio_producto_precio_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprecios',
            name='motivo',
            field=models.CharField(blank=True, choices=[('manual', 'Actualización manual'), ('lote', 'Precio desde lote'), ('proveedor', 'Actualización de proveedor'), ('descuento', 'Aplicación de descuento'), ('aumento', 'Aumento de precio'), ('correccion', 'Corrección de precio'), ('inicial', 'Precio inicial')], default='manual', max_length=100),
        ),
        migrations.AddField(
            model_name='historialprecios',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones sobre el cambio de precio'),
        ),
        migrations.AddField(
            model_name='historialprecios',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio anterior (para calcular variaciones)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historialprecios',
            name='tipo_precio',
            field=models.CharField(choices=[('producto', 'Precio del Producto'), ('proveedor', 'Precio de Proveedor'), ('lote', 'Precio de Lote')], default='proveedor', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialprecios',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor (opcional - solo para precios de compra)', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor'),
        ),
    ]
