# Generated by Django 5.0.1 on 2025-06-14 00:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_historialprecios_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del producto (JPG, PNG, WebP, máx. 10MB)', max_length=255, null=True, verbose_name='Imagen del Producto'),
        ),
    ]
